Docs: explain how to run/debug e2e tests
knative-sandbox/eventing-rabbitmq pull request #529
Opened 2021-11-29 17:35 UTC by KauzClay

# Changes
- 🎁📄 Add docs to explain how to run the e2e tests, and add some tips for debugging tests.
- No user related impact, solely for contributors.

/kind documentation

Fixes #517

2021-11-30 14:19 UTC, gabo1208 requested changes

2021-11-30 14:19 UTC, gabo1208 commented on test/e2e/README.md
> +  **Note:** If the credentials don't work, you can also try `guest` for both username and password.
The guest credentials should be when debugging the VHost Source tests, this because the way the cluster is been created

2021-11-30 17:01 UTC, gabo1208 approved these changes

2021-11-30 21:11 UTC, KauzClay commented
/assign @markusthoemmes

2021-12-01 13:46 UTC, gvmw commented
/unassign @markusthoemmes
/assign @benmoss

2021-12-01 14:08 UTC, gvmw commented
/lgtm

2021-12-01 14:09 UTC, gvmw commented
/approve

2021-12-02 15:00 UTC, benmoss commented
/approve

2021-12-02 15:16 UTC, benmoss commented
@KauzClay can you fix the lint warnings?

2021-12-03 14:28 UTC, benmoss commented
/lgtm
/approve

thanks for sticking with us through the the slow feedback loops @KauzClay :smil

2021-12-03 14:48 UTC, benmoss commented
/hold cancel

2021-12-03 14:48 UTC, merged