Broker and source docs improvements
knative-sandbox/eventing-rabbitmq pull request #555
Opened 2021-12-17 16:54 UTC by gabo1208

# Changes

- 🎁 New samples docs and files
- 🧹 Updated old source and broker docs (still some work to do but its a start)

/kind documentation

Fixes #553 

**Release Note**

```release-note
Improved Brokers and Sources Readme docs and Samples description and files.
```

**Docs**

```docs

```

2022-01-07 14:50 UTC, xtreme-sameer-vohra requested changes

2022-01-12 22:49 UTC, xtreme-sameer-vohra requested changes
Thanks @gabo1208 it's looking great :)
Added some minor comments and there are a few comments from before.

2022-01-12 22:49 UTC, xtreme-sameer-vohra commented on samples/broker-trigger/README.md
Doing `install the Broker running:` won't have the RMQ pre-requisites available, which are required. Does it make sense to link to https://github.com/knative-sandbox/eventing-rabbitmq/blob/main/broker/operator-based.md#rabbitmq-operator-based-knative-eventing-broker ?

2022-01-12 22:49 UTC, xtreme-sameer-vohra commented on samples/broker-trigger/README.md
> +default   http://default-broker-ingress.broker-trigger-demo.svc.cluster.local   2m39s   True
Thanks for fixing the formatting.
Thoughts on moving `kubectl -n broker-trigger-demo get brokers` to after the Broker install ?

2022-01-13 16:26 UTC, xtreme-sameer-vohra requested changes
It would be valuable for the samples to simplify the setup required to run them, so does it make sense to refer to the releases of the Broker and Source and remove references to building them from source code ?

2022-01-13 16:26 UTC, xtreme-sameer-vohra commented on samples/broker-trigger/README.md
> +Same as listed [here](../../broker/README.md#prerequisites)
```suggestion
Same as listed [here](../../broker/README.md)
```

`#prerequisites` doesn't appear to be defined 🤔

2022-01-13 16:26 UTC, xtreme-sameer-vohra commented on samples/broker-trigger/README.md
> +Now install the Broker running:
The previous step points to the [installation](https://github.com/gabo1208/eventing-rabbitmq/blob/broker-and-source-docs-improvements/broker/operator-based.md#installation) which would include installing the rabbitmq-broker.yaml
Is this step required ?

2022-01-13 16:26 UTC, xtreme-sameer-vohra commented on samples/source/README.md
> +Same as listed [here](../../source/DEVELOPMENT.md#prerequisites)
What are the pre-requisites from the development side required for trying this sample ?

2022-01-13 16:26 UTC, xtreme-sameer-vohra commented on samples/source/README.md
>  install the Source running:
```suggestion
Install the Source by running:
```

2022-01-13 17:19 UTC, xtreme-sameer-vohra commented on broker/README.md
> +- [Autoscaling](#autoscaling)
```suggestion
```
Dead link

2022-01-14 01:50 UTC, gabo1208 commented on source/README.md
> +  - Configure channel config properties based on this documentation.
```suggestion

  - Configure channel config properties based on this documentation.
```

2022-01-18 19:44 UTC, xtreme-sameer-vohra commented
/lgtm

2022-01-18 19:44 UTC, xtreme-sameer-vohra commented
Thanks for driving this @gabo1208  👍

2022-01-18 19:45 UTC, xtreme-sameer-vohra approved these changes

2022-01-18 19:45 UTC, merged