Adds policyInformer to Trigger controller
knative-sandbox/eventing-rabbitmq pull request #602
Opened 2022-02-03 23:45 UTC by gab-satchi

Observed a state where a Trigger can be in an unready state even though the Queue and DLQ are both in Ready. 

# Changes
The trigger controller will now watch for events in policies and enqueue the trigger if it's the owner of the policy.

/kind bug

Addresses some of the flakes observed in #598

2022-02-03 23:45 UTC, gab-satchi commented on test/e2e/kind.yaml
> +  image: kindest/node:${KIND_K8S_VERSION}@${KIND_K8S_DIGEST}
Temporary till we get a signal with these changes.

2022-02-03 23:46 UTC, gab-satchi commented
/hold

2022-02-04 14:21 UTC, gabo1208 commented
/test all

2022-02-04 14:22 UTC, gabo1208 commented
/test ?

2022-02-04 22:05 UTC, gab-satchi commented
This change seems to consistently get passed the `Setup` phase but there is now a flake that could happen in the `Requirement` phase. Opened #603 to address it

2022-02-08 19:34 UTC, gab-satchi commented
/hold cancel

2022-02-08 21:03 UTC, ikvmw requested changes
I and @gabo1208 looked it at and we have a question. Informers set up handlers to enqueue events, but where is the actual processing is done? Like we see only producing part, where is Policy changes processed.

2022-02-08 21:34 UTC, gab-satchi commented
> I and @gabo1208 looked it at and we have a question. Informers set up handlers to enqueue events, but where is the actual processing is done? Like we see only producing part, where is Policy changes processed.

This repo doesn't reconcile the Policy, that's done by the topology-operator. We do however rely on the Policy's status in order to set the Trigger's status. The handler will trigger a reconcile on the Trigger/Broker when a policy they own is updated. 

Any Policy changes will get reflected onto the Trigger/Broker through this [codeblock](https://github.com/knative-sandbox/eventing-rabbitmq/blob/00e9d0ca8889ca635fdd95899ad8f753481db2b0/pkg/rabbit/service.go#L94-L117)

2022-02-09 14:40 UTC, ikvmw approved these changes

2022-02-09 14:40 UTC, merged

2022-02-09 22:42 UTC, ikvmw commented
Per zoom: Informer's handler enqueues event that will be later picked up by controller loop: https://github.com/knative-sandbox/eventing-rabbitmq/blob/56717fb27f1980c4306b9988bc570cd1f919e3a8/vendor/knative.dev/pkg/controller/controller.go#L493.

Which shows us that knative uses its own controller framework and not the one from Operator SDK - https://github.com/kubernetes-sigs/controller-runtime